name: Fetch all roles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
    
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'

      
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/376681942354/locations/global/workloadIdentityPools/github-identity-pool/providers/github-oidc-provider'
        service_account: 'github-iam-monitor@gcp-iam-monitor-bot.iam.gserviceaccount.com'
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Fetch all IAM Roles'
      run: ./fetch-all-roles.sh
    - name: 'Commit, Tag, and Release'
      run: ./.github/commit-and-release.sh
      env:
        TOKEN: ${{ secrets.TOKEN }}
        NAME: ${{ secrets.NAME }}
        EMAIL: ${{ secrets.EMAIL }}
