name: Fetch all roles

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
    
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/376681942354/locations/global/workloadIdentityPools/github-identity-pool/providers/github-oidc-provider'
        service_account: 'github-iam-monitor@gcp-iam-monitor-bot.iam.gserviceaccount.com'
    - name: set gcp project
      run: gcloud config set project gcp-iam-monitor-bot
    - name: fetch all iam roles
      run: ./fetch-all-roles.sh
    - name: commit, tag, and release
      run: ./.github/commit-and-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
