name: Fetch all roles

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"
    
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/376681942354/locations/global/workloadIdentityPools/github-identity-pool/providers/github-oidc-provider'
        service_account: 'github-iam-monitor@gcp-iam-monitor-bot.iam.gserviceaccount.com'
    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Fetch all IAM Roles'
      run: ./fetch-all-roles.sh
    - name: 'Commit, Tag, and Release'
      run: ./.github/commit-and-release.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITUB_TOKEN }}
